### ISSUE TITLE
Incorrectly parsing geos version 3.8.0

### ISSUE THREAD

**Issue by azhi** [dark-panda/ffi-geos#29]
In 3.8.0, geos devs decided to remove git revision hash from capi version (https://github.com/libgeos/geos/commit/7699310f0bc7b3f2a6f300e72164d3fab3e76646#diff-8dd96440c9832c59176dcaa7c346b982R3549).
Unfortunately, they left whitespace at the end, so now this regex is broken again - https://github.com/dark-panda/ffi-geos/blob/2662d8523574ff174f05af116d392fd9460aa839/lib/ffi-geos.rb#L1284-L1289.

Example of broken version:
```
> Geos.version
=> "3.8.0-CAPI-1.13.1 "
> Geos::GEOS_VERSION
=> "0.0.0"
```

PS: I've create a [PR](https://github.com/libgeos/geos/pull/270) to geos to remove unnecessary whitespace, so it hopefully will be fixed in next geos release. Not sure if you want to hack release regex to make 3.8.0 work.

**Comment by dark-panda** [comment]
Fixed in 9c51273f41ce8206b4fe60779d8a74ef4b21cce0. Will release a new version soon, just going to do a little bit of clean up first.
